### ISSUE TITLE
Problem displaying attachment of new message

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#118]
@goofy-bz reported he had problem displaying attachment of a message he just received. Reloading the page made the bug disappear.
I was able to reproduce the issue once.

**Comment by clochix** [comment]
This one was hard to reproduce and investigate. It's related to the realtime update. When we sent a message over sockets, we forgot to convert it to client format, so some data was missing, like the URLs of the attachments.

So, when you open a new message, we send a request to update the Seen flag. Once the request is over we store the updated message on client side. But we receive next a realtime update for the message, badly formated, and display it again, with the missing url.

I fixed the bug on server side, and added some code to also handle it on client side : if an attachment has no URL, we log it and try to guess the URL.

@aenario, could you review the server side patch?

@poupotte: it's really hard to reproduce. One way is to display a message with attachments, unfold the headers to see the attachments, and play with message flags: mark it read / unread… The attached files should always have an URL.

**Comment by poupotte** [comment]
@clochix  I tried to reproduce this issue with your protocol. When I mark read my mail, I receive an error. I have this message in my console :  
```
PATCH https://bellot-zoe.cozycloud.cc/apps/emails/message/883f98d550b30fe64ed500538313c6ff [HTTP/1.1 500 Internal Server Error 264ms]
"Error in messagePatch" "883f98d550b30fe64ed500538313c6ff" Object { message: "Invalid system flag \NONJUNK", stack: "Error: Invalid system flag \NONJUNK
    at Connection._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1463:11)
    at Parser.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:173:10)
    at Parser.emit (events.js:95:17)
    at Parser._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:174:10)
    at Parser._parse (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:138:16)
    at Parser._tryread (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:82:15)
    at CleartextStream.Parser._cbReadable (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:53:12)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7", source: "protocol" }
```

**Comment by clochix** [comment]
You should be able to test once #134 is fixed.

**Comment by poupotte** [comment]
I try to reproduce your test but I can't access to my attachments. I open an issue (#189) for that.

**Comment by poupotte** [comment]
It seems work with your test. Thanks @clochix .
