### ISSUE TITLE
Problem to mark unread a specific email

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#134]
I try to unread a message (with an attachment and open) and I receive an error. I have this message in my console :  
```
PATCH https://bellot-zoe.cozycloud.cc/apps/emails/message/883f98d550b30fe64ed500538313c6ff [HTTP/1.1 500 Internal Server Error 264ms]
"Error in messagePatch" "883f98d550b30fe64ed500538313c6ff" Object { message: "Invalid system flag \NONJUNK", stack: "Error: Invalid system flag \NONJUNK
    at Connection._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1463:11)
    at Parser.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:173:10)
    at Parser.emit (events.js:95:17)
    at Parser._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:174:10)
    at Parser._parse (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:138:16)
    at Parser._tryread (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:82:15)
    at CleartextStream.Parser._cbReadable (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:53:12)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7", source: "protocol" }
```
According to @clochix , NONJUNK tag, it is a tag added by thunderbird.

P.S. : Mark unread other mails works.

**Comment by clochix** [comment]
AFAIK, JUNK and NONJUNK are flags used by Thunderbird (among others) but not supported by every email server.
When TB thinks a message is spam, it adds the Junk flag. If the user marks the message as not spam, TB then use the NoJunk flag to remember user's decision.
I checked and OVH server doesn't seem to support both of this flags.

**Comment by aenario** [comment]
This is a server-side problem and is due to the distinction between server-supported flags and user-custom keywords. 

It should have been fixed by https://github.com/cozy/cozy-emails/commit/0f2a802174970b4186656b584a0e80153924813e , It is probably an error with the patch handling code.  @poupotte , if you can reproduce easily, could you get the request body ?

**Comment by poupotte** [comment]
Request body : 
```
[{"op":"remove","path":"/flags/1"},{"op":"replace","path":"/flags/0","value":"NonJunk"}]
```

**Comment by poupotte** [comment]
Reopen due to #163.

**Comment by poupotte** [comment]
It works well, thanks @aenario
