### ISSUE TITLE
I can't see my mail attachments

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#189]
When I click to display a mail attachment, I receive in an other browser window : 

```
Connect
500 TypeError: Object #<LaterStream> has no method 'on'

    at Object.module.exports.attachment [as handle] (/usr/local/cozy/apps/emails/build/server/controllers/messages.js:70:10)
    at next_layer (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/route.js:103:13)
    at /usr/local/cozy/apps/emails/build/server/controllers/messages.js:42:12
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:59:20
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:65:18
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage. (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

```

**Comment by poupotte** [comment]
Morever with my new mail, I don't receive attachments : mail appears without attachment.

**Comment by poupotte** [comment]
It works well. Thanks @aenario .
