### ISSUE TITLE
Error sending message with attachment

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#352]
From our user @Abbo44

He gets a 500 when sending a message with an attachment. Here's the call stack:

    TypeError: Cannot call method 'getBinary' of undefined
    at contentToBuffer (/usr/local/cozy/apps/emails/build/server/controllers/messages.js:226:30)
    at async.mapSeries.message.attachments (/usr/local/cozy/apps/emails/build/server/controllers/messages.js:262:14)
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:249:17
    at iterate (/usr/local/cozy/apps/emails/node_modules/async/lib/async.js:149:13)
    at async.eachSeries (/usr/local/cozy/apps/emails/node_modules/async/lib/async.js:165:9)
    at _asyncMap (/usr/local/cozy/apps/emails/node_modules/async/lib/async.js:248:13)
    at Object.mapSeries (/usr/local/cozy/apps/emails/node_modules/async/lib/async.js:231:23)
    at /usr/local/cozy/apps/emails/build/server/controllers/messages.js:261:18
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:610:21
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:249:17

**Comment by poupotte** [comment]
It should be fixed in the new version. @Abbo44, it's ok for you ?

**Comment by Abbo44** [comment]
Yes , it's ok !

**Comment by poupotte** [comment]
Thanks :)
