### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#365]
Not sure of which action resulted in this crash, because I was using the client while tests ran in parallel. I think I was trying to remove a draft just created by the tests, so that may have had the Recent flag.

    cozy-emails/node_modules/imap/lib/Connection.js:620
            throw new Error('The keyword "' + items[i]
                  ^
    Error: The keyword "\Recent" contains invalid characters
      at ImapConnection.Connection._store (cozy-emails/node_modules/imap/lib/Connection.js:620:15)
      at ImapConnection.Connection.setKeywords (cozy-emails/node_modules/imap/lib/Connection.js:584:8)
      at async.series.imap.multicopy.k (cozy-emails/server/models/message.coffee:703:34)
      at cozy-emails/node_modules/async/lib/async.js:610:21
      at cozy-emails/node_modules/async/lib/async.js:249:17
      at iterate (cozy-emails/node_modules/async/lib/async.js:149:13)
      at cozy-emails/node_modules/async/lib/async.js:160:25
      at cozy-emails/node_modules/async/lib/async.js:251:21
      at ImapConnection.<anonymous> (cozy-emails/node_modules/async/lib/async.js:615:34)
      at ImapConnection.Connection._resTagged (cozy-emails/node_modules/imap/lib/Connection.js:1496:22)
      at Parser.<anonymous> (cozy-emails/node_modules/imap/lib/Connection.js:173:10)
      at Parser.emit (events.js:95:17)
      at Parser._resTagged (cozy-emails/node_modules/imap/lib/Parser.js:174:10)
      at Parser._parse (cozy-emails/node_modules/imap/lib/Parser.js:138:16)
      at Parser._tryread (cozy-emails/node_modules/imap/lib/Parser.js:82:15)
      at CleartextStream.Parser._cbReadable (cozy-emails/node_modules/imap/lib/Parser.js:53:12)
      at CleartextStream.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:410:10)
      at _stream_readable.js:403:7
      at process._tickCallback (node.js:419:13)

**Comment by aenario** [comment]
The code has changed too much since this error happened. I am pretty sure it cant happens anymore as we only use addFlags & removeFlags.

**Comment by poupotte** [comment]
Ok, thanks @aenario . I close this issue, don't hesiste to reopn it if problem reappaers.
