### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-emails#383]
The following error was reported by an user.

It appears the IMAP server replied with the code "System error (Failure)" when the app attempted to open a box to fetch one mail.

I will ask the user for more information about provider. 

```
DBUG models:message fetchOrUpdate
DBUG models:message fetch
DBUG imap:pool XXXX _deQueue/stopTimer
DBUG imap:pool XXXX _deQueue/free
DBUG imap:pool XXXX begin wrapped task
DBUG imap:pool XXXX wrapped box opened { [Error: System error (Failure)] textCode: undefined, source: 'protocol' }
Error: System error (Failure)
at ImapConnection.Connection._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1463:11)
at Parser.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:173:10)
at Parser.emit (events.js:95:17)
at Parser._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:174:10)
at Parser._parse (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:138:16)
at Parser._tryread (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:82:15)
at CleartextStream.Parser._cbReadable (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:53:12)
at CleartextStream.emit (events.js:92:17)
at emitReadable_ (_stream_readable.js:427:10)
at _stream_readable.js:420:7
```

**Comment by poupotte** [comment]
@aenario, have you more information about this issue ?

**Comment by poupotte** [comment]
We can't reproduce this issue. If someone has this bugs, don't hesitate to reopen it
