### ISSUE TITLE
Stacktrace after sending an email

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#437]
I got an error message and saw this in my logs. I think it's a big issue because it happens many times:

```
INFO models:account FETCHING ACCOUNT Cozy : 2
INFO models:account   BOXES  0 BOXES TO DESTROY
INFO models:mailbox IMAP REFRESH INBOX UID 24816:25815
INFO models:message createFromImapMessage INBOX 25814
INFO models:message createFromImapMessage INBOX 25813
INFO models:mailbox IMAP REFRESH Sent UID 5700:6699
[Tue, 12 May 2015 10:13:43 GMT] - POST /message - 200 - 881.055 ms -  3402
[Tue, 12 May 2015 10:14:13 GMT] - POST /message - 200 - 873.280 ms -  3402
[Tue, 12 May 2015 10:14:43 GMT] - POST /message - 200 - 773.875 ms -  3520
[Tue, 12 May 2015 10:15:13 GMT] - POST /message - 200 - 812.494 ms -  3663
[Tue, 12 May 2015 10:15:43 GMT] - POST /message - 200 - 824.710 ms -  3993
[Tue, 12 May 2015 10:16:14 GMT] - POST /message - 200 - 1210.611 ms -  4123
[Tue, 12 May 2015 10:16:43 GMT] - POST /message - 200 - 869.588 ms -  4617
[Tue, 12 May 2015 10:17:13 GMT] - POST /message - 200 - 834.224 ms -  4427
[Tue, 12 May 2015 10:17:45 GMT] - POST /message - 200 - 21380.850 ms -  4541

/usr/local/cozy/apps/emails/node_modules/cozydb/lib/utils/type_checking.js:84
      return value.map(function(item) {
                   ^
TypeError: Object 4468cdf0bba650fb6c29ee3ea60f9ee3 has no method 'map'
    at exports.castValue.castValue (/usr/local/cozy/apps/emails/node_modules/cozydb/lib/utils/type_checking.js:84:20)
    at exports.castObject.castObject (/usr/local/cozy/apps/emails/node_modules/cozydb/lib/utils/type_checking.js:113:22)
    at Function.Model.cast (/usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:248:14)
    at Function.module.exports.CozyBackedModel.cast (/usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:309:57)
    at Message.Model (/usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:263:24)
    at Message.CozyBackedModel (/usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:286:52)
    at new Message (/usr/local/cozy/apps/emails/build/server/models/message.js:29:42)
    at /usr/local/cozy/apps/emails/build/server/models/message.js:247:16
    at Array.map (native)
    at /usr/local/cozy/apps/emails/build/server/models/message.js:246:23
```

**Comment by frankrousseau** [comment]
In fact it breaks my email client totally.

**Comment by frankrousseau** [comment]
It didn't happen when I had only one email box. Now I have two (both from OVH) it doesn't work.

**Comment by clochix** [comment]
One more regression due to #405 (inReplyTo must be a string in NodeMailer, internaly we use an array).
This only happens when `in-reply-to` is set, so when replying to or forwarding messages.

**Comment by poupotte** [comment]
@frankrousseau , have you still this error in your Cozy ?

**Comment by frankrousseau** [comment]
Yep it works. thank you.
