### ISSUE TITLE
Error when trying to forward message with attachments

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#440]
Server error when trying to forward a message with attachments.

**Comment by clochix** [comment]
@aenario would you mind having a look at this one ? Thanks !

**Comment by clochix** [comment]
FTR, here's the stack:
```
EROR +0000 errorhandler [TypeError: Cannot call method 'getBinary' of undefined]
TypeError: Cannot call method 'getBinary' of undefined
  at contentToBuffer (cozy-emails/server/controllers/messages.coffee:194:34)
  at async.mapSeries.message.attachments (cozy-emails/server/controllers/messages.coffee:237:13)
  at cozy-emails/node_modules/async/lib/async.js:249:17
  at iterate (cozy-emails/node_modules/async/lib/async.js:149:13)
  at async.eachSeries (cozy-emails/node_modules/async/lib/async.js:165:9)
  at _asyncMap (cozy-emails/node_modules/async/lib/async.js:248:13)
  at Object.mapSeries (cozy-emails/node_modules/async/lib/async.js:231:23)
  at cozy-emails/server/controllers/messages.coffee:236:15
  at cozy-emails/node_modules/async/lib/async.js:610:21
  at cozy-emails/node_modules/async/lib/async.js:249:17
  at iterate (cozy-emails/node_modules/async/lib/async.js:149:13)
  at async.eachSeries (cozy-emails/node_modules/async/lib/async.js:165:9)
  at _asyncMap (cozy-emails/node_modules/async/lib/async.js:248:13)
  at Object.mapSeries (cozy-emails/node_modules/async/lib/async.js:231:23)
  at Object.async.series (cozy-emails/node_modules/async/lib/async.js:608:19)
  at module.exports.send (cozy-emails/server/controllers/messages.coffee:359:11)
  at Layer.handle [as handle_request] (cozy-emails/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
  at next (cozy-emails/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
  at module.exports.fetchMaybe (cozy-emails/server/controllers/messages.coffee:30:10)
  at Layer.handle [as handle_request] (cozy-emails/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
  at next (cozy-emails/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
  at cozy-emails/server/controllers/accounts.coffee:20:9
  at cozy-emails/server/models/account.coffee:47:13
  at cozy-emails/node_modules/cozydb/lib/model.js:59:20
  at cozy-emails/node_modules/cozydb/lib/cozymodel.js:65:18
  at parseBody (cozy-emails/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
  at IncomingMessage.<anonymous> (cozy-emails/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:419:13)
```

**Comment by poupotte** [comment]
It works well. Thanks @aenario
