### ISSUE TITLE
Random bugs in conversation navigation

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#441]
When I navigate in my conversations, sometimes, I receive some errors `Argh, I'm unable to perform this action, please try again`. I have this error in my console : 
```
PUT 
https://bellot-zoe.cozycloud.cc/apps/emails/messages/batchAddFlag [HTTP/1.1 500 Internal Server Error 489ms]
GET 
https://bellot-zoe.cozycloud.cc/apps/emails/messages/batchFetch [HTTP/1.1 500 Internal Server Error 56ms]
GET 
https://bellot-zoe.cozycloud.cc/apps/emails/messages/batchFetch [HTTP/1.1 500 Internal Server Error 48ms]
POST 
https://bellot-zoe.cozycloud.cc/apps/emails/activity [HTTP/1.1 500 Internal Server Error 63ms]
"TypeError: message.trim is not a function" "https://bellot-zoe.cozycloud.cc/apps/emails/js/app.js" 452 29 TypeError: message.trim is not a function
Stack trace:
LayoutActionCreator.notify@https://bellot-zoe.cozycloud.cc/apps/emails/js/app.js:452:30
LayoutActionCreator.alertError@https://bellot-zoe.cozycloud.cc/apps/emails/js/app.js:445:1
MessageActionCreator.mark/afterUpdate@https://bellot-zoe.cozycloud.cc/apps/emails/js/app.js:801:9
module.exports.batchAddFlag/<@https://bellot-zoe.cozycloud.cc/apps/emails/js/app.js:14357:16
Request.prototype.callback@https://bellot-zoe.cozycloud.cc/apps/emails/js/vendor.js:34012:3
Request/<@https://bellot-zoe.cozycloud.cc/apps/emails/js/vendor.js:33683:5
Emitter.prototype.emit@https://bellot-zoe.cozycloud.cc/apps/emails/js/vendor.js:33145:7
Request.prototype.end/xhr.onreadystatechange@https://bellot-zoe.cozycloud.cc/apps/emails/js/vendor.js:34094:5
 "LayoutActionCreator.notify@https://bellot-zoe.cozycloud.cc/apps/emails/js/app.js:452:30
LayoutActionCreator.alertError@https://bellot-zoe.cozycloud.cc/apps/emails/js/app.js:445:1
MessageActionCreator.mark/afterUpdate@https://bellot-zoe.cozycloud.cc/apps/emails/js/app.js:801:9
module.exports.batchAddFlag/<@https://bellot-zoe.cozycloud.cc/apps/emails/js/app.js:14357:16
Request.prototype.callback@https://bellot-zoe.cozycloud.cc/apps/emails/js/vendor.js:34012:3
Request/<@https://bellot-zoe.cozycloud.cc/apps/emails/js/vendor.js:33683:5
Emitter.prototype.emit@https://bellot-zoe.cozycloud.cc/apps/emails/js/vendor.js:33145:7
Request.prototype.end/xhr.onreadystatechange@https://bellot-zoe.cozycloud.cc/apps/emails/js/vendor.js:34094:5
" app.js:9677:0

"Error in fetchConversation" "c2989f8f-2af2-402f-a458-7dd11b02a90e" "Error: socket hang up"
```

**Comment by clochix** [comment]
According to the stack trace, there are in fact two errors : 
 - a network error on server side. The remote IMAP server closed the connection : "Error in fetchConversation" "c2989f8f-2af2-402f-a458-7dd11b02a90e" "Error: socket hang up"
 - an error on client side when trying to display this error.

Unfortunately, it will be hard to debug.

**Comment by poupotte** [comment]
I have this error in my server mail if it can help.

I had lots errors (about 10) 'Bad request'.

```
BadRequest: Bad request : No conversationIDs, conversationID, or messageIDs in body.
    at module.exports.batchFetch (/usr/local/cozy/apps/emails/build/server/controllers/messages.js:446:17)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/index.js:321:12)
    at next (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/index.js:261:10)
    at logger (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/morgan/index.js:108:5)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)

/usr/local/cozy/apps/emails/node_modules/cozydb/lib/utils/type_checking.js:84
      return value.map(function(item) {
                   ^
TypeError: Object a50d6ec3154960c7619612932ee218a8 has no method 'map'
    at exports.castValue.castValue (/usr/local/cozy/apps/emails/node_modules/cozydb/lib/utils/type_checking.js:84:20)
    at exports.castObject.castObject (/usr/local/cozy/apps/emails/node_modules/cozydb/lib/utils/type_checking.js:113:22)
    at Function.Model.cast (/usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:248:14)
    at Function.module.exports.CozyBackedModel.cast (/usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:309:57)
    at Message.Model (/usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:263:24)
    at Message.CozyBackedModel (/usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:286:52)
    at new Message (/usr/local/cozy/apps/emails/build/server/models/message.js:29:42)
    at /usr/local/cozy/apps/emails/build/server/models/message.js:247:16
    at Array.map (native)
    at /usr/local/cozy/apps/emails/build/server/models/message.js:246:23
```

**Comment by poupotte** [comment]
This issue seems fixed. Thanks @clochix ! :)
