### ISSUE TITLE
Cannot send email anymore

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#542]
I got this error everytime I try to send an email (at the beginning, everything was working well): 

```
[Thu, 02 Jul 2015 16:41:30 GMT] - POST /message - 400 - 15129.178 ms -  71
EROR +0051 controllers:activity { type: 'error',
  error: 
   { msg: 'TypeError: message is undefined',
     full: 'TypeError: message is undefined',
     stack: 'MessageStore</onReceiveRawMessage@https://frank.cozycloud.cc/apps/emails/js/app.js:13031:5\nMessageStore</MessageStore.prototype.__bindHandlers/<@https://frank.cozycloud.cc/apps/emails/js/app.js:13263:7\nStore</_processBinding/this.dispatchToken</<@https://frank.cozycloud.cc/apps/emails/js/app.js:10329:18\nDispatcher</Dispatcher.prototype._invokeCallback@https://frank.cozycloud.cc/apps/emails/js/app.js:10203:5\nDispatcher</Dispatcher.prototype.dispatch@https://frank.cozycloud.cc/apps/emails/js/app.js:10173:23\nAppDispatcher</AppDispatcher.prototype.handleViewAction@https://frank.cozycloud.cc/apps/emails/js/app.js:1184:5\nMessageActionCreator.send/<@https://frank.cozycloud.cc/apps/emails/js/app.js:749:1\nmodule.exports.messageSend/<@https://frank.cozycloud.cc/apps/emails/js/app.js:15278:16\nRequest.prototype.callback@https://frank.cozycloud.cc/apps/emails/js/vendor.js:34012:3\nRequest/<@https://frank.cozycloud.cc/apps/emails/js/vendor.js:33683:5\nEmitter.prototype.emit@https://frank.cozycloud.cc/apps/emails/js/vendor.js:33145:7\nRequest.prototype.end/xhr.onreadystatechange@https://frank.cozycloud.cc/apps/emails/js/vendor.js:34094:5\n' },
  url: 'https://frank.cozycloud.cc/apps/emails/js/app.js',
  line: 13031,
  col: 4,
  href: 'https://frank.cozycloud.cc/apps/emails/#account/95c21ed1e699b1ab48e2be72c3647e91/mailbox/95c21ed1e699b1ab48e2be72c3649a80/conversation/924bee58-27d4-4cfb-bd91-480ae80e3f90/fd4ce610aeff70c0f39129cd720c7a07/' }
EROR +0001 controllers:activity MessageStore</onReceiveRawMessage@https://frank.cozycloud.cc/apps/emails/js/app.js:13031:5
MessageStore</MessageStore.prototype.__bindHandlers/<@https://frank.cozycloud.cc/apps/emails/js/app.js:13263:7
Store</_processBinding/this.dispatchToken</<@https://frank.cozycloud.cc/apps/emails/js/app.js:10329:18
Dispatcher</Dispatcher.prototype._invokeCallback@https://frank.cozycloud.cc/apps/emails/js/app.js:10203:5
Dispatcher</Dispatcher.prototype.dispatch@https://frank.cozycloud.cc/apps/emails/js/app.js:10173:23
AppDispatcher</AppDispatcher.prototype.handleViewAction@https://frank.cozycloud.cc/apps/emails/js/app.js:1184:5
MessageActionCreator.send/<@https://frank.cozycloud.cc/apps/emails/js/app.js:749:1
module.exports.messageSend/<@https://frank.cozycloud.cc/apps/emails/js/app.js:15278:16
Request.prototype.callback@https://frank.cozycloud.cc/apps/emails/js/vendor.js:34012:3
Request/<@https://frank.cozycloud.cc/apps/emails/js/vendor.js:33683:5
Emitter.prototype.emit@https://frank.cozycloud.cc/apps/emails/js/vendor.js:33145:7
Request.prototype.end/xhr.onreadystatechange@https://frank.cozycloud.cc/apps/emails/js/vendor.js:34094:5

[Thu, 02 Jul 2015 16:41:30 GMT] - POST /activity - 200 - 2.655 ms -  2
EROR +0003 errorhandler error handler called with Error: Invalid login
    at SMTPConnection._formatError (/usr/local/cozy/apps/emails/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:388:15)
    at SMTPConnection._actionAUTHComplete (/usr/local/cozy/apps/emails/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:863:30)
    at SMTPConnection.<anonymous> (/usr/local/cozy/apps/emails/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:243:22)
    at SMTPConnection._processResponse (/usr/local/cozy/apps/emails/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:511:16)
    at SMTPConnection._onData (/usr/local/cozy/apps/emails/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:357:10)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
[Thu, 02 Jul 2015 16:41:35 GMT] - POST /message - 500 - 5199.898 ms -  -
EROR +0000 models:account CANT REFRESH ACCOUNT Cozy { [AccountConfigError: on field 'auth']
  name: 'AccountConfigError',
  field: 'auth',
  message: 'on field \'auth\'',
  stack: '',
  original: { [Error: Authentication failed.] textCode: 'AUTHENTICATIONFAILED', source: 'authentication' } }
INFO +0001 config initial refresh completed
INFO +0000 config Initialization complete
EROR +0000 models:account CANT REFRESH ACCOUNT Cozy { [AccountConfigError: on field 'auth']
  name: 'AccountConfigError',
  field: 'auth',
  message: 'on field \'auth\'',
  stack: '',
  original: { [Error: Authentication failed.] textCode: 'AUTHENTICATIONFAILED', source: 'authentication' } }
EROR +0000 models:account CANT REFRESH ACCOUNT Cozy { [AccountConfigError: on field 'auth']
  name: 'AccountConfigError',
  field: 'auth',
  message: 'on field \'auth\'',
  stack: '',
  original: { [Error: Authentication failed.] textCode: 'AUTHENTICATIONFAILED', source: 'authentication' } }
leartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
```

**Comment by clochix** [comment]
@frankrousseau according to the logs, it seems related to an authentication error. Do you still receive messages in your Cozy account ? If so, could you try again to send a message ?

**Comment by clochix** [comment]
My bad, it's an authentication error with the SMTP server, so could you check its parameters ?
server: ssl0.ovh.net
port: 993
SSL: true
STARTTLS: false
and no advanced parameters

**Comment by frankrousseau** [comment]
I didn't know why my password changed. I put the old one instead and it now works.
