### ISSUE TITLE
Error on refresh of empty boxes

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-emails#548]
```
/usr/local/cozy/apps/emails/build/server/controllers/mailboxes.js:70
        ref = counts[req.mailbox.id], total = ref.total, recent = ref.recent, 
                                                 ^
TypeError: Cannot read property 'total' of undefined
    at /usr/local/cozy/apps/emails/build/server/controllers/mailboxes.js:70:50
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:163:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:254:18
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

https://github.com/cozy/cozy-emails/blob/fdc7bbd77a2dc1f2b30ea8878b05ecd2e13d8a9b/server/controllers/mailboxes.coffee#L47

https://forum.cozy.io/t/emails-probleme-sur-les-boites-vides/894

**Comment by clochix** [comment]
Do you know the status of the issue?

**Comment by aenario** [comment]
This should have been fixed in https://github.com/aenario/cozy-emails/commit/fe46a9d34c099b50b8718741895a1c64cdd26057

**Comment by clochix** [comment]
Ok, let's close it, thanks @aenario
