### ISSUE TITLE
Emails application not starting

### ISSUE THREAD

**Issue by nicodel** [cozy/cozy-emails#574]
Hi,
I have Emails application trying to launch for nearly 30 minutes now, and the icon is still spinning.
Instance hosted on Cozy infrastructure (nicolas-6)
Data System: 2.0.6
Proxy: 2.0.2
Home: 2.0.4
Controller: 2.0.27
Emails: 0.9.5

Here are the Emails logs:
```
INFO +0000 models:account FETCHING ACCOUNT nicodel : 9
INFO +0000 models:account   BOXES  0 BOXES TO DESTROY
INFO +0001 models:message createFromImapMessage INBOX 6605
WARN +0000 models:mailbox 4932 + 1 < 4977 on INBOX
WARN +0002 models:mailbox refreshFast fail (Error:     WRONG STATE
    at Mailbox._refreshDeleted (/usr/local/cozy/apps/emails/build/server/models/mailbox.js:549:23)
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:439:20
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:528:18
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:157:25
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:521:22
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:935:18
    at Object.async.eachSeries (/usr/local/cozy/apps/emails/node_modules/async/lib/async.js:145:20)
    at Message.module.exports.Message.storeAttachments (/usr/local/cozy/apps/emails/build/server/models/message.js:748:18)
    at /usr/local/cozy/apps/emails/build/server/models/message.js:741:27
    at /usr/local/cozy/apps/emails/build/server/utils/socket_handler.js:100:14), trying deep
INFO +0000 models:mailbox IMAP REFRESH INBOX UID 1:6606
INFO +0000 models:message createFromImapMessage Trash 1599
INFO +0000 models:message createFromImapMessage Trash 1600
INFO +0000 models:message createFromImapMessage Trash 1601
INFO +0000 models:message createFromImapMessage Trash 1602
INFO +0000 models:message createFromImapMessage Trash 1603
INFO +0000 models:message createFromImapMessage Trash 1604
INFO +0000 models:message createFromImapMessage Trash 1605
WARN +0000 models:mailbox 154 + 0 < 156 on Sent
WARN +0001 models:mailbox refreshFast fail (Error:     WRONG STATE
    at Mailbox._refreshDeleted (/usr/local/cozy/apps/emails/build/server/models/mailbox.js:549:23)
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:439:20
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:528:18
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:157:25
    at /usr/local/cozy/apps/emails/build/server/utils/socket_handler.js:111:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:34:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:112:18
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.emit (events.js:117:20)), trying deep
INFO +0000 models:mailbox IMAP REFRESH Sent UID 1:157
INFO +0000 models:account FETCHING ACCOUNT gmail : 21
INFO +0000 models:account   BOXES  0 BOXES TO DESTROY
WARN +0000 models:mailbox 6579 + 0 < 6587 on INBOX
WARN +0001 models:mailbox refreshFast fail (Error:     WRONG STATE
    at Mailbox._refreshDeleted (/usr/local/cozy/apps/emails/build/server/models/mailbox.js:549:23)
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:439:20
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:528:18
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:157:25
    at /usr/local/cozy/apps/emails/build/server/utils/socket_handler.js:111:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:34:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:112:18
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.emit (events.js:117:20)), trying deep
INFO +0000 models:mailbox IMAP REFRESH INBOX UID 9280:19279
INFO +0000 models:mailbox IMAP REFRESH INBOX UID 1:9279
INFO +0000 models:message MAIL [Gmail]/Important:14971 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14972 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14973 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14974 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14975 ADDED TO BOX
WARN +0000 models:mailbox 12177 + 5 < 12193 on [Gmail]/Important
WARN +0000 models:mailbox refreshFast fail (Error:     WRONG STATE
    at Mailbox._refreshDeleted (/usr/local/cozy/apps/emails/build/server/models/mailbox.js:549:23)
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:439:20
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:528:18
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:157:25
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:521:22
    at /usr/local/cozy/apps/emails/build/server/models/message.js:645:14
    at /usr/local/cozy/apps/emails/build/server/utils/socket_handler.js:111:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:34:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:112:18
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)), trying deep
INFO +0000 models:mailbox IMAP REFRESH Important UID 4988:14987
INFO +0000 models:message MAIL [Gmail]/Important:14986 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14985 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14984 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14983 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14982 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14981 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14980 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14979 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14978 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14977 ADDED TO BOX
INFO +0000 models:message MAIL [Gmail]/Important:14976 ADDED TO BOX
INFO +0000 models:mailbox IMAP REFRESH Important UID 1:4987
WARN +0000 models:mailbox 1764 + 0 < 1765 on [Gmail]/Messages envoyÃ©s
WARN +0003 models:mailbox refreshFast fail (Error:     WRONG STATE
    at Mailbox._refreshDeleted (/usr/local/cozy/apps/emails/build/server/models/mailbox.js:549:23)
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:439:20
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:528:18
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:157:25
    at /usr/local/cozy/apps/emails/build/server/utils/socket_handler.js:111:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:34:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:112:18
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.emit (events.js:117:20)), trying deep
INFO +0000 models:mailbox IMAP REFRESH Messages envoyÃ©s UID 1:1843
WARN +0000 models:mailbox 17397 + 0 < 17419 on [Gmail]/Tous les messages
WARN +0001 models:mailbox refreshFast fail (Error:     WRONG STATE
    at Mailbox._refreshDeleted (/usr/local/cozy/apps/emails/build/server/models/mailbox.js:549:23)
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:439:20
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:528:18
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:157:25
    at /usr/local/cozy/apps/emails/build/server/utils/socket_handler.js:111:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:34:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:112:18
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.emit (events.js:117:20)), trying deep
INFO +0000 models:mailbox IMAP REFRESH Tous les messages UID 13379:23378
INFO +0000 models:mailbox IMAP REFRESH Tous les messages UID 3379:13378
INFO +0000 models:mailbox IMAP REFRESH Tous les messages UID 1:3378
INFO +0000 models:message MAIL Trash:6666 ADDED TO BOX
INFO +0000 models:message MAIL Trash:6667 ADDED TO BOX
INFO +0000 models:message createFromImapMessage Spam 1640
INFO +0000 config initial refresh completed
INFO +0001 config Initialization complete
```
This sequence is repeating itself endlessly, its seems. It did not identify weird logs from Home, Data System or Proxy linked to that.

**Comment by aenario** [comment]
Hi @nicodel,

I just connected to your cozy to check its status and it appears the email app is now started.

Do you still experiment problems to access it ?

**Comment by nicodel** [comment]
Hi @aenario ,
I clicked on the Email spinning icon, and the page displayed a "Impossible to display page" message.
I clicked on the "Refresh" button and it finally displayed the Email application.
False alarm ?

**Comment by aenario** [comment]
Well, something is definitively wrong here. Basically, home failed to see that emails was started.
But this is most probably an error with cozy-home or cozy-controller. If you manage to reproduce, could you try to get the logs from the home client ?

Closing this issue in the meantime.

**Comment by nicodel** [comment]
I'll do.

**Comment by aenario** [comment]
Great. Thanks for reporting !
