### ISSUE TITLE
Error when emptying trash folder

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-emails#599]
Hi,

Here is the error I got when emptying the trash from on of my email accounts (0.9.8): 

```
/usr/local/cozy/apps/emails/build/server/models/mailbox.js:290
            return Message.safeRemoveAllFromBox(box.id, function(err) {
                           ^
TypeError: Object function Message() {
    return Message.__super__.constructor.apply(this, arguments);
  } has no method 'safeRemoveAllFromBox'
    at /usr/local/cozy/apps/emails/build/server/models/mailbox.js:290:28
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:610:21
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:249:17
    at iterate (/usr/local/cozy/apps/emails/node_modules/async/lib/async.js:149:13)
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:160:25
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:251:21
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:615:34
    at ImapConnection.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:424:7)
    at ImapConnection.Connection._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1496:22)
    at Parser.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:173:10)
```

**Comment by clochix** [comment]
Thanks for reporting @ZeHiro.
Seems like we removed this methind during the last refactoring but forgot some calls :-S

**Comment by Geabulek** [comment]
I'm commenting here as it may be related but while doing the same action, I got "Error: Network batchDelete"

**Comment by poupotte** [comment]
I don't receive anymore error when a expunge my trash. 

However, it seems doesn't work each time. Indeed, I have expunge 3 times my trash of my first mailbox to delete all messages. For the second, I have to expunge twice : 

Server logs in first time : I don't receive error but message stay on trash (with or without refresh)
```
INFO +3099 mailbox:controller Expunging 531c6a5a3dd1ef34671f6a19e277912c
[Tue, 18 Aug 2015 07:37:38 GMT] - DELETE /mailbox/531c6a5a3dd1ef34671f6a19e277912c/expunge - 200 - 3741.480 ms -  3920
EROR +0378 imap:pool active connection imap.googlemail.com:993 closed false
```

Server log the second time : I don't receive error and message disappear (without  refresh )
```
NFO +9547 mailbox:controller Expunging 531c6a5a3dd1ef34671f6a19e277912c
[Tue, 18 Aug 2015 07:39:26 GMT] - DELETE /mailbox/531c6a5a3dd1ef34671f6a19e277912c/expunge - 200 - 11216.179 ms -  3920
INFO +0001 models:message createFromImapMessage INBOX 24230
INFO +0000 models:message createFromImapMessage INBOX 24231
WARN +0000 process:box_refresh_fast 14361 + 2 < 14544 on undefined
WARN +0000 process/refreshpick refreshFast fail, trying deep
INFO +0000 process:box_refresh_deep IMAP REFRESH INBOX UID 14233:24232
```

**Comment by poupotte** [comment]
It works well now. Thanks @aenario
