### ISSUE TITLE
Problem of instability

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#603]
From a user : 
`
Ma boite email ne semble plus être rafraîchie, et quand je clique sur les deux derniers emails (lesquels ne sont jamais marqués comme "lu") une petite fenêtre pop intitulée "message flag ko", contenant un lien hypertexte intitulé "1 ERREUR". ce lien ouvre une fenêtre m'indiquant de vous transmettre le message suivant :
Error: Network batchAddFlag
`
Cet utilisateur ne peut également plus supprimer de messages. Il reçoit ```Error: Network batchDelete```
Une mise à jour de l'application n'a pas aidé.

**Comment by Abbo44** [comment]
Problème présent aussi chez moi :+1:

**Comment by frankrousseau** [comment]
@Abbo44 Est-ce que cela se produit avec la dernière version ?

**Comment by Abbo44** [comment]
Oui toujours
Le 4 sept. 2015 17:53, Frank Rousseau <notifications@github.com> a écrit :@Abbo44 Est-ce que cela se produit avec la dernière version ?

**Comment by Abbo44** [comment]
Au niveau des logs

```
DBUG +0001 errorhandler ERROR HANDLER CALLED { [Error: Authentication failed.] textCode: undefined, source: 'authentication' }
EROR +0001 errorhandler error handler called with Error: Authentication failed.
    at ImapConnection.Connection._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1463:11)
    at Parser.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:173:10)
    at Parser.emit (events.js:95:17)
    at Parser._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:174:10)
    at Parser._parse (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:138:16)
    at Parser._tryread (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:82:15)
    at CleartextStream.Parser._cbReadable (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:53:12)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7

```

**Comment by poupotte** [comment]
@frankrousseau and @Abbo44 Do you have still problem of instabilty ?

**Comment by clochix** [comment]
Ping @frankrousseau and @Abbo44 
Any news regarding this one ?

**Comment by kimmy1** [comment]
what is this?

**Comment by clochix** [comment]
Sorry @kimmy1 I really don't know why Github noticed you of this :-S

**Comment by frankrousseau** [comment]
It's ok for me.

**Comment by kimmy1** [comment]
Trey

**Comment by frankrousseau** [comment]
I close this issue so @kimmy1 is not spammed anymore. @Abbo44 If the problem is still there, please open a new issue.

**Comment by kimmy1** [comment]
Who is this emailing carl howard?

**Comment by kimmy1** [comment]
Who is this
