### ISSUE TITLE
Importation crashes on a large Mailbox

### ISSUE THREAD

**Issue by Gara64** [cozy/cozy-emails#614]
During the importation of a large Gmail box (more than 10 000 mails), the app crashes and eventually displays a 504 error. 
The logs return this : 

```
INFO +0000 models:message createFromImapMessage INBOX 7243
DBUG +0000 models:message flags =  []
DBUG +0000 models:message findConversationID
DBUG +0002 models:message findConversationID [] RentrÃ©e littÃ©raire 2013 : les incontournables et les pÃ©pites Ã  dÃ©couvrir ! true
DBUG +0007 models:message found similar 0
DBUG +0000 models:message pickConversationID

/usr/local/cozy/apps/emails/node_modules/html-to-text/node_modules/underscore/underscore.js:1315
    var accum = Array(Math.max(0, n));
                ^
RangeError: Invalid array length
    at Function._.times (/usr/local/cozy/apps/emails/node_modules/html-to-text/node_modules/underscore/underscore.js:1315:17)
    at /usr/local/cozy/apps/emails/node_modules/html-to-text/lib/formatter.js:125:10
    at Function._.each._.forEach (/usr/local/cozy/apps/emails/node_modules/html-to-text/node_modules/underscore/underscore.js:153:9)
    at /usr/local/cozy/apps/emails/node_modules/html-to-text/lib/formatter.js:113:6
    at Function._.each._.forEach (/usr/local/cozy/apps/emails/node_modules/html-to-text/node_modules/underscore/underscore.js:153:9)
    at Object.formatTable [as table] (/usr/local/cozy/apps/emails/node_modules/html-to-text/lib/formatter.js:110:4)
    at /usr/local/cozy/apps/emails/node_modules/html-to-text/lib/html-to-text.js:110:25
    at Function._.each._.forEach (/usr/local/cozy/apps/emails/node_modules/html-to-text/node_modules/underscore/underscore.js:153:9)
    at walk (/usr/local/cozy/apps/emails/node_modules/html-to-text/lib/html-to-text.js:77:4)
    at /usr/local/cozy/apps/emails/node_modules/html-to-text/lib/formatter.js:120:16
```

**Comment by clochix** [comment]
Thanks for reporting @Gara64,
The problem isn't related to the number of messages to import. It's one message content that make the parsing crash (maybe the message “Rentrée littéraire 2013 : les incontournables et les pépites à  découvrir”).
I'll catch this error so it doesn't make the server crash.

**Comment by poupotte** [comment]
Thanks @clochix :)

**Comment by Gara64** [comment]
Thanks!
