### ISSUE TITLE
Error to remove message

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#618]
I remove lots of messages in mailbox. After about 10 messages removed, I can't remove others.
Server error is : 
```
DBUG +6030 errorhandler ERROR HANDLER CALLED [TypeError: Cannot read property 'mailboxIDs' of null]
EROR +0001 errorhandler error handler called with TypeError: Cannot read property 'mailboxIDs' of null
    at /usr/local/cozy/apps/emails/build/server/models/message.js:669:30
    at Array.filter (native)
    at Function.module.exports.Message.batchMove (/usr/local/cozy/apps/emails/build/server/models/message.js:667:25)
    at Function.module.exports.Message.batchTrash (/usr/local/cozy/apps/emails/build/server/models/message.js:796:17)
    at module.exports.batchTrash (/usr/local/cozy/apps/emails/build/server/controllers/messages.js:496:18)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at handleMessages (/usr/local/cozy/apps/emails/build/server/controllers/messages.js:459:12)
    at /usr/local/cozy/apps/emails/build/server/controllers/messages.js:463:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:57:20
[Mon, 07 Sep 2015 06:14:33 GMT] - PUT /messages/batchTrash - 500 - 13.220 ms -  -
mails/build/server/models/message.js:669:30
    at Array.filter (native)
    at Function.module.exports.Message.batchMove (/usr/local/cozy/apps/emails/build/server/models/message.js:667:25)
    at Function.module.exports.Message.batchTrash (/usr/local/cozy/apps/emails/build/server/models/message.js:796:17)
    at module.exports.batchTrash (/usr/local/cozy/apps/emails/build/server/controllers/messages.js:496:18)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at handleMessages (/usr/local/cozy/apps/emails/build/server/controllers/messages.js:459:12)
    at /usr/local/cozy/apps/emails/build/server/controllers/messages.js:463:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:57:20
ode_modules/cozydb/lib/cozymodel.js:63:18
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at IncomingMessage.emit (events.js:117:20)
NotFound: Not Found: No message found
    at module.exports.batchSend (/usr/local/cozy/apps/emails/build/server/controllers/messages.js:484:17)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at handleMessages (/usr/local/cozy/apps/emails/build/server/controllers/messages.js:459:12)
    at /usr/local/cozy/apps/emails/build/server/controllers/messages.js:463:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/model.js:57:20
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:63:18
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at IncomingMessage.emit (events.js:117:20)
```

**Comment by poupotte** [comment]
I can't reproduce it.
