### ISSUE TITLE
[client] TypeError: Cannot set property 'uniq' of null

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#619]
Error seen in the logs of an user who's trying to create an account:
```
EROR +0000 controllers:activity TypeError: Cannot set property 'uniq' of null
    at AccountStore.<anonymous> (https://xxxx.cozycloud.cc/apps/emails/js/app.js:12154:18)
    at Object.ID_1 (https://xxxx.cozycloud.cc/apps/emails/js/app.js:10357:27)
    at AppDispatcher.module.exports.Dispatcher._invokeCallback (https://xxxx.cozycloud.cc/apps/emails/js/app.js:10231:24)
    at AppDispatcher.module.exports.Dispatcher.dispatch (https://xxxx.cozycloud.cc/apps/emails/js/app.js:10201:28)
    at AppDispatcher.handleViewAction (https://xxxx.cozycloud.cc/apps/emails/js/app.js:1199:10)
    at Object.module.exports.AccountActionCreator._setNewAccountError (https://xxxx.cozycloud.cc/apps/emails/js/app.js:223:26)
    at https://xxxx.cozycloud.cc/apps/emails/js/app.js:144:30
    at https://xxxx.cozycloud.cc/apps/emails/js/app.js:15472:16
    at Request.callback (https://xxxx.cozycloud.cc/apps/emails/js/vendor.js:34012:3)
    at Request.<anonymous> (https://xxxx.cozycloud.cc/apps/emails/js/vendor.js:33683:10)
```

**Comment by poupotte** [comment]
I don't arrive to reproduce this issue. @clochix, do you have more information about user account ?

**Comment by clochix** [comment]
Sorry, I don't have more informations ☹

But I think I know where it come from: in AccountActionCreator.create, we call _setNewAccountError if error is not null or account is null. So, if account and error are null, we call the method with a null error and AccountStore crash handling NEW_ACCOUNT_ERROR

So the problem seems to happen on account creation when error is null but also account. I don't know how to reproduce this case (I thought I already fixed this one or a very similar one, but am unable to find it)
