### ISSUE TITLE
Bad request : Cant refresh a non RFC4551 box

### ISSUE THREAD

**Issue by Abbo44** [cozy/cozy-emails#620]
Hello,  when i try to click on the reception box in my ISEN mail, i have this error;
```
<html>
  <head>
    <meta charset='utf-8'> 
    <title>BadRequest: Bad request : Cant refresh a non RFC4551 box</title>
    <style>* {
  margin: 0;
  padding: 0;
  outline: 0;
}

body {
  padding: 80px 100px;
  font: 13px "Helvetica Neue", "Lucida Grande", "Arial";
  background: #ECE9E9 -webkit-gradient(linear, 0% 0%, 0% 100%, from(#fff), to(#ECE9E9));
  background: #ECE9E9 -moz-linear-gradient(top, #fff, #ECE9E9);
  background-repeat: no-repeat;
  color: #555;
  -webkit-font-smoothing: antialiased;
}
h1, h2 {
  font-size: 22px;
  color: #343434;
}
h1 em, h2 em {
  padding: 0 5px;
  font-weight: normal;
}
h1 {
  font-size: 60px;
}
h2 {
  margin-top: 10px;
}
ul li {
  list-style: none;
}
#stacktrace {
  margin-left: 60px;
}
</style>
  </head>
  <body>
    <div id="wrapper">
      <h1>Connect</h1>
      <h2><em>400</em> BadRequest: Bad request : Cant refresh a non RFC4551 box</h2>
      <ul id="stacktrace"><li>    at module.exports.refresh (/usr/local/cozy/apps/emails/build/server/controllers/mailboxes.js:33:17)</li><li>    at Layer.handle [as handle_request] (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)</li><li>    at next (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/route.js:110:13)</li><li>    at Route.dispatch (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/route.js:91:3)</li><li>    at Layer.handle [as handle_request] (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)</li><li>    at /usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/index.js:267:22</li><li>    at param (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/index.js:340:14)</li><li>    at param (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/index.js:356:14)</li><li>    at Function.proto.process_params (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/index.js:400:3)</li><li>    at next (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/index.js:261:10)</li></ul>
    </div>
  </body>
</html>
```

**Comment by Abbo44** [comment]
duplicate issue : https://github.com/cozy/cozy-emails/issues/547
