### ISSUE TITLE
Wrong error message on account creation: [Object object]

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#639]
When a user enter wrong account configuration options, [he gets this error message](https://forum.cozy.io/t/email-retour-sur-la-prise-en-main/1317) : `[Object object]`

**Comment by rgarrigue** [comment]
Creating the first account, a @gmail.com, I click CHECK CONNECTION and end up with this error message. Here is the output from `tail -f /usr/local/var/log/cozy/emails.log`

```
UG +0000 imap:pool Attempting connection
DBUG +0001 imap:pool { user: 'rg@gmail.com',
  password: '****',
  host: 'imap.gmail.com',
  port: 993,
  tls: true,
  tlsOptions: { rejectUnauthorized: false },
  autotls: 'required' }
DBUG +0984 imap:pool tmp connection error on imap.gmail.com:993
DBUG +0001 imap:pool RAW ERROR { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  source: 'socket' }
DBUG +5005 imap:pool tmp makeConnection
DBUG +0000 imap:pool Attempting connection
DBUG +0001 imap:pool { user: 'rg@gmail.com',
  password: '****',
  host: 'imap.gmail.com',
  port: 993,
  tls: true,
  tlsOptions: { rejectUnauthorized: false },
  autotls: 'required' }
DBUG +1025 imap:pool tmp connection error on imap.gmail.com:993
DBUG +0001 imap:pool RAW ERROR { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  source: 'socket' }
DBUG +5008 imap:pool tmp makeConnection
DBUG +0001 imap:pool Attempting connection
DBUG +0000 imap:pool { user: 'rg@gmail.com',
  password: '****',
  host: 'imap.gmail.com',
  port: 993,
  tls: true,
  tlsOptions: { rejectUnauthorized: false },
  autotls: 'required' }
DBUG +1049 imap:pool tmp connection error on imap.gmail.com:993
DBUG +0000 imap:pool RAW ERROR { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  source: 'socket' }
DBUG +0000 imap:pool tmp giveup { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  source: 'socket' }
DBUG +0000 imap:pool tmp destroy
DBUG +0000 imap:pool tmp closeConnections
DBUG +0000 errorhandler ERROR HANDLER CALLED { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  source: 'socket' }
EROR +0001 errorhandler error handler called with Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
[Thu, 24 Sep 2015 12:06:00 GMT] - PUT /accountUtil/check - 500 - 13246.723 ms -  -
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```
