### ISSUE TITLE
Server error: maximum request size exceeded

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#669]
Emails version 0.9.15

```
Error: parse error: maximum request size exceeded
    at ImapConnection.Connection._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1463:11)
    at Parser.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:173:10)
    at Parser.emit (events.js:95:17)
    at Parser._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:174:10)
    at Parser._parse (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:138:16)
    at Parser._tryread (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:82:15)
    at CleartextStream.Parser._cbReadable (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:53:12)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7

```

**Comment by clochix** [comment]
This seems to be an error sent by remote IMAP server when user tries to delete messages. See [this thread](https://forum.cozy.io/t/email-non-effacable/1590).

**Comment by clochix** [comment]
One more [testimony](https://forum.cozy.io/t/emails-autre-retour-de-premiere-utilisation/1627).

**Comment by vdubus** [comment]
I got the same error when trying to get my e-mails from [Laposte.net](https://www.laposte.net/accueil) using Cozy Emails v1.0.33.

```
DBUG +0001 imap:reporter constructor process mailbox-refresh-deep2c04a3da-a438-4d1b-8515-fed1d1541637
DBUG +0000 imap:reporter run process mailbox-refresh-deep2c04a3da-a438-4d1b-8515-fed1d1541637
DBUG +0000 process:box_refresh_deep imap_refreshStep initial range: undefined:undefined
DBUG +0000 process:box_refresh_deep diff initial range: undefined:undefined
DBUG +0031 process:box_refresh_deep computeNextStep initial range: undefined:undefined next 11912
DBUG +0000 process:box_refresh_deep nextStepEnd  range: 1:10000
INFO +0000 process:box_refresh_deep IMAP REFRESH INBOX UID 1:10000
DBUG +0028 imap:extensions imap#fetchMetadata 1 10000
DBUG +0022 imap:extensions imap#fetchMetadata#results undefined 2921
DBUG +0011 imap:pool 6c2738aa8c02182387b3c0945713181a wrapped operation completed
DBUG +0000 process:box_refresh_deep diff#results
DBUG +0001 errorhandler ERROR HANDLER CALLED { [Error: parse error: maximum request size exceeded] textCode: undefined, source: 'protocol' }
EROR +0001 errorhandler error handler called with Error: parse error: maximum request size exceeded
    at ImapConnection.Connection._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1463:11)
    at Parser.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:173:10)
    at Parser.emit (events.js:95:17)
    at Parser._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:174:10)
    at Parser._parse (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:138:16)
    at Parser._tryread (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:82:15)
    at CleartextStream.Parser._cbReadable (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:53:12)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at _stream_readable.js:403:7
[Fri, 18 Mar 2016 22:46:04 GMT] - GET /refresh/6c2738aa8c02182387b3c0945713779f?deep=false - 500 - 98.617 ms -  922
DBUG +0003 processes:scheduler process finished mailbox-refresh0b7c9184-cf92-4c3b-aa2e-67ba1c9d973f Error: parse error: maximum request size exceeded
DBUG +0000 processes:scheduler Scheduler.doNext already running =  false
DBUG +0000 processes:scheduler Scheduler.onIdle
DBUG +0000 processes:scheduler nothing to do, waiting 10 MIN
[Fri, 18 Mar 2016 22:46:04 GMT] - GET /mailbox/6c2738aa8c02182387b3c0945713779f/?sort=-date - 200 - 128.203 ms -  79172
DBUG +5099 sockethandler updateClientScope Zk00SwidSU23kay2AAAB { mailboxID: '6c2738aa8c02182387b3c0945713779f',
  before: '2016-03-15T21:27:15.000Z' }
[Fri, 18 Mar 2016 22:46:36 GMT] - GET /mailbox/6c2738aa8c02182387b3c094570aa445/?sort=-date - 200 - 308.045 ms -  482675
[Fri, 18 Mar 2016 22:46:39 GMT] - GET /mailbox/6c2738aa8c02182387b3c094570aa7b5/?sort=-date - 200 - 174.979 ms -  277520
```

Do you need more information ?

**Comment by clochix** [comment]
Thanks for your feedback @vdubus ☺
@aenario any thought on this?

**Comment by aenario** [comment]
I will have to make some test, but we will probably need to catch this error and lower batch size when we get it. I will ask for it on next email:server sprint.
