### ISSUE TITLE
Server error: undefined is not a function

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#670]
Email version: 0.9.15
```
/usr/local/cozy/apps/emails/build/server/processes/_base.js:70
          results.push(cb(err, arg1, arg2, arg3, arg4));
                       ^
TypeError: undefined is not a function
    at /usr/local/cozy/apps/emails/build/server/processes/_base.js:70:24
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:700:17
    at /usr/local/cozy/apps/emails/build/server/processes/message_remove_by_account.js:49:18
    at /usr/local/cozy/apps/emails/build/server/processes/message_remove_by_account.js:78:16
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:254:18
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

**Comment by poupotte** [comment]
Duplicate with #666

**Comment by clochix** [comment]
Closing as this is a duplicate.
