### ISSUE TITLE
Error: NotFound: Not Found: No message found

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#681]
```
NotFound: Not Found: No message found
    at module.exports.batchSend (/usr/local/cozy/apps/emails/build/server/controllers/messages.js:484:17)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/emails/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at handleMessages (/usr/local/cozy/apps/emails/build/server/controllers/messages.js:459:12)
    at /usr/local/cozy/apps/emails/build/server/models/message.js:220:14
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:254:18
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
```

**Comment by poupotte** [comment]
@clochix, do you have more details ?

* How this error appears ?
* What consequences ?

**Comment by clochix** [comment]
Sorry, I have no more information, it was an error I saw in emails error log. But it seems to be a quite uncommon error, as I don't remember seeing it recently. Maybe can we close this issue.

**Comment by poupotte** [comment]
Thanks @clochix , I close this issue, if you see a similar error don't hesistate to reopen it.
