### ISSUE TITLE
IMAP error: Invalid uidset

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#684]
Found in server error logs:
```
DBUG +0000 errorhandler ERROR HANDLER CALLED { [Error: Error in IMAP command UID STORE: Invalid uidset] textCode: undefined, source: 'protocol' }
EROR +0001 errorhandler error handler called with Error: Error in IMAP command UID STORE: Invalid uidset
    at ImapConnection.Connection._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1463:11)
    at Parser.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:173:10)
    at Parser.emit (events.js:95:17)
    at Parser._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:174:10)
    at Parser._parse (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:138:16)
    at Parser._tryread (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:82:15)
    at CleartextStream.Parser._cbReadable (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:53:12)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
[Mon, 23 Nov 2015 17:54:01 GMT] - PUT /messages/batchAddFlag - 500 - 242.996 ms -  -

```

**Comment by poupotte** [comment]
This issue is not relevant anymore because we're working on a new Emails version.
