### ISSUE TITLE
Création d'un nouveau message : "Message contains bare newlines"

### ISSUE THREAD

**Issue by EtienneM** [cozy/cozy-emails#695]
J'ai 2 comptes configurés pour lire mes e-mails. Avec l'un des deux comptes, lorsque je souhaite envoyer un nouveau message, j'obtiens le message d'erreur "Une erreur est survenue : Message contains bare newlines". Ça ne le fait pas avec les deux comptes. Ça semble proche du problème décrit dans le ticket #119 mais il devrait être résolu. 

Tout est à jour sur ma plateforme. J'ai installé Cozy sur un Raspberry Pi 2.

**Comment by clochix** [comment]
Hello @EtienneM,

Cette erreur est renvoyée par le serveur SMTP distant, est-ce que tu pourrais nous dire quel est le prestataire ?

**Comment by EtienneM** [comment]
Il s'agit de l'université de Strasbourg. Il me semble qu'ils utilisent SOGo.

**Comment by clochix** [comment]
Merci de ta réponse, nous allons creuser ☺

**Comment by EtienneM** [comment]
Pas de soucis ! 

Si vous avez besoin de plus d'info, n'hésitez pas. Je suis informaticien donc je peux comprendre si vous me parlez en barbu ;)

**Comment by clochix** [comment]
Y a-t-il du neuf sur ce ticket ? Un autre cozynaute, Jacques S., me signale le même message d'erreur lorsqu'il essaie d'envoyer un message. Comme il est sur notre plateforme de test, nous pouvons plus facilement reproduire et essayer de corriger l'erreur.
Ping @aenario @jsilvestre

**Comment by clochix** [comment]
Quelques logs…
```
DBUG +5434 controllers:mesage send
DBUG +0000 imap:reporter constructor process message-save-or-send95945fd0-23dc-4425-a101-197365b5e377
DBUG +0000 imap:reporter run process message-save-or-send95945fd0-23dc-4425-a101-197365b5e377
DBUG +0001 process:message_saving gathering attachments
DBUG +0111 errorhandler ERROR HANDLER CALLED { [Error: Message contains bare newlines] textCode: undefined, source: 'protocol' }
EROR +0002 errorhandler error handler called with Error: Message contains bare newlines
    at ImapConnection.Connection._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1463:11)
    at Parser.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:173:10)
    at Parser.emit (events.js:95:17)
    at Parser._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:174:10)
    at Parser._parse (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:138:16)
    at Parser._tryread (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:82:15)
    at CleartextStream.Parser._cbReadable (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:53:12)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
[Mon, 07 Mar 2016 09:02:42 GMT] - POST /message - 500 - 118.941 ms -  898

```
