### ISSUE TITLE
[server] error in server/processes/_base.js

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#713]
```
/usr/local/cozy/apps/emails/build/server/processes/_base.js:70
          results.push(cb(err, arg1, arg2, arg3, arg4));
                       ^
TypeError: undefined is not a function
    at /usr/local/cozy/apps/emails/build/server/processes/_base.js:70:24
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:693:24
    at /usr/local/cozy/apps/emails/build/server/processes/message_remove_by_account.js:57:20
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:196:29
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:121:18
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
``

See https://github.com/cozy/cozy-emails/blob/development/server/processes/_base.coffee#L49

**Comment by aenario** [comment]
This should have been fixed in https://github.com/cozy/cozy-emails/commit/8a878de7316c07963acbcd84c800909526dc25a4

**Comment by poupotte** [comment]
Duplicate #666
