### ISSUE TITLE
PasswordEncryptedError 

### ISSUE THREAD

**Issue by Fenntasy** [cozy/cozy-emails#834]
Hello, 

I have this bug that cozy encouraged me to post. My mails worked yesterday (I have all previous emails in store) but can't seem to work today because of this error: 

```
{"original":null,"response":{"req":{"_query":["deep=false"],"method":"GET","url":"refresh/fda94937b3c20d21f6d9a78b33005b48?deep=false","header":{},"_header":{},"_callbacks":{"$end":[null]},"xhr":{},"_timeout":0},"xhr":{},"text":"{\"error\":true,\"name\":\"PasswordEncryptedError\",\"message\":\"Password is still encrypted in DS for account Test\",\"stack\":\"PasswordEncryptedError: Password is still encrypted in DS for account Test\
    at module.exports.makeIMAPConfig.makeIMAPConfig (/usr/local/cozy/apps/emails/build/server/imap/account2config.js:104:21)\
    at ImapPool.module.exports.ImapPool._makeConnection (/usr/local/cozy/apps/emails/build/server/imap/pool.js:83:12)\
    at ImapPool.module.exports.ImapPool._deQueue (/usr/local/cozy/apps/emails/build/server/imap/pool.js:258:21)\
    at ImapPool._deQueue (/usr/local/cozy/apps/emails/build/server/imap/pool.js:3:57)\
    at ImapPool.module.exports.ImapPool.doLaterWithBox (/usr/local/cozy/apps/emails/build/server/imap/pool.js:374:17)\
    at Mailbox.doLaterWithBox (/usr/local/cozy/apps/emails/build/server/models/mailbox.js:145:39)\
    at MailboxRefreshDeep.module.exports.MailboxRefreshDeep.getDiff (/usr/local/cozy/apps/emails/build/server/processes/mailbox_refresh_deep.js:145:25)\
    at /usr/local/cozy/apps/emails/build/server/processes/mailbox_refresh_deep.js:3:57\
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:610:21\
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:249:17\"}","statusText":"Internal Server Error","statusCode":500,"status":500,"statusType":5,"info":false,"ok":false,"clientError":false,"serverError":true,"error":{"status":500,"method":"GET","url":"refresh/fda94937b3c20d21f6d9a78b33005b48?deep=false"},"accepted":false,"noContent":false,"badRequest":false,"unauthorized":false,"notAcceptable":false,"notFound":false,"forbidden":false,"headers":{"date":"Mon, 02 May 2016 09:19:01 GMT","etag":"W/\"1UsAf4/Ml3kmEEkFXchmnQ==\"","server":"nginx/1.6.2","connection":"keep-alive","x-powered-by":"Express","content-length":"1254","content-type":"application/json; charset=utf-8"},"header":{"date":"Mon, 02 May 2016 09:19:01 GMT","etag":"W/\"1UsAf4/Ml3kmEEkFXchmnQ==\"","server":"nginx/1.6.2","connection":"keep-alive","x-powered-by":"Express","content-length":"1254","content-type":"application/json; charset=utf-8"},"type":"application/json","charset":"utf-8","body":{"error":true,"name":"PasswordEncryptedError","message":"Password is still encrypted in DS for account Test","stack":"PasswordEncryptedError: Password is still encrypted in DS for account Test
    at module.exports.makeIMAPConfig.makeIMAPConfig (/usr/local/cozy/apps/emails/build/server/imap/account2config.js:104:21)
    at ImapPool.module.exports.ImapPool._makeConnection (/usr/local/cozy/apps/emails/build/server/imap/pool.js:83:12)
    at ImapPool.module.exports.ImapPool._deQueue (/usr/local/cozy/apps/emails/build/server/imap/pool.js:258:21)
    at ImapPool._deQueue (/usr/local/cozy/apps/emails/build/server/imap/pool.js:3:57)
    at ImapPool.module.exports.ImapPool.doLaterWithBox (/usr/local/cozy/apps/emails/build/server/imap/pool.js:374:17)
    at Mailbox.doLaterWithBox (/usr/local/cozy/apps/emails/build/server/models/mailbox.js:145:39)
    at MailboxRefreshDeep.module.exports.MailboxRefreshDeep.getDiff (/usr/local/cozy/apps/emails/build/server/processes/mailbox_refresh_deep.js:145:25)
    at /usr/local/cozy/apps/emails/build/server/processes/mailbox_refresh_deep.js:3:57
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:610:21
    at /usr/local/cozy/apps/emails/node_modules/async/lib/async.js:249:17"}},"status":500}
CLOSE
```

When I test the connexion, it says that my params are ok but I can't fetch mails anymore.

**Comment by clochix** [comment]
Hi @Fenntasy,

Could-you try to restart the Email application ? (go to “My Apps” screen at the bottom of home page, find the Email application, click on the small icon to stop it, then on its name to restart it). It may be enough to fix you issue.

(we are aware of this kind of problems, which occurs sometime when the whole server is restarted. A fix is in progress)

**Comment by Fenntasy** [comment]
Thanks, that worked :) I'll deal with it that way for the time being;
