### ISSUE TITLE
Unable to access e-mails on gmail

### ISSUE THREAD

**Issue by svandecappelle** [cozy/cozy-emails#871]
Folder are synchronised but doesn't show any messages.
Any folders show "0 messages" tooltip.

An error is present into the log file:
`/usr/local/var/log/cozy/emails-err.log`

```
^[[31mEROR^[[39m +0595 imap:pool active connection imap.gmail.com:993 closed false
^[[31mEROR^[[39m +0001 errorhandler error handler called with Error: Server error occured.
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:85:27
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
^[[31mEROR^[[39m +0375 imap:pool active connection imap.gmail.com:993 closed false
^[[31mEROR^[[39m +0000 errorhandler error handler called with Error: Server error occured.
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:85:27
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
^[[31mEROR^[[39m +0375 imap:pool active connection imap.gmail.com:993 closed false
```

Version installed: 
0.9.22 - started
https://github.com/cozy/cozy-emails(master)

Regards
Thanks =)

**Comment by svandecappelle** [comment]
Today, the emails are accessible. I don't know why. 
Maybe it's due to a long time synchronisation to gmail.
