### ISSUE TITLE
Trash mailbox is not saved when creating/updating account

### ISSUE THREAD

**Issue by hmsuchier** [cozy/cozy-emails#910]
Hello,
 It looks like I can't save my "trash" mailbox when creating a new account (as a consequence, I can't use the acccount). Looking at what is sent by the browser when selecting a box in the dropdown, I can't see any sent information related to this. Am I missing something ?
Thanks!

**Comment by hmsuchier** [comment]
It looks like the server side takes correctly into account the "trashMailbox" parameter when it is sent by the client. So the problem is actually the client side not sending this information.

**Comment by clochix** [comment]
Thanks for reporting.

A huge [refactoring is in progress](https://forum.cozy.io/t/maintenance-of-email-application/2320) on the email application and the Account screen has been fully rewritten. The new version should be available in a few weeks.

If I understand well, you try to connect to an account that has no Trash folder for now, creating the Trash folder on the account creation screen?

**Comment by hmsuchier** [comment]
Thanks for replying. I just installed a Cozy instance and when creating my very first account on the Emails application, i can't go further than configuration screen, because trash mailbox can't be saved (actually no existing trash folder for the concerned email). Using firefox console, I forced a trashMailbox parameter on the query that is triggered by mailbox selection dropdown change, and this allows to save the parameter. Now i can read my mails.

**Comment by novski** [comment]
Hi, i have the same issue with my icloud e-mail account. 
I can see the folders but it throughs errors when i click on any one. In as out several more and trash. the settings don't let me store the trash folder.
It says: please transmit this to cozy: 

{"original":null,"response":{"req":{"_query":["deep=false"],"method":"GET","url":"refresh/3b2a9391467d9286773782e0f55c38cc?deep=false","header":{},"_header":{},"_callbacks":{"$end":[null]},"xhr":{},"_timeout":0},"xhr":{},"text":"{\"error\":true,\"name\":\"Error\",\"message\":\"Command line too large\",\"stack\":\"Error: Command line too large\\n    at ImapConnection.Connection._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1463:11)\\n    at Parser.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:173:10)\\n    at Parser.emit (events.js:95:17)\\n    at Parser._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:174:10)\\n    at Parser._parse (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:138:16)\\n    at Parser._tryread (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:82:15)\\n    at CleartextStream.Parser._cbReadable (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:53:12)\\n    at CleartextStream.emit (events.js:92:17)\\n    at emitReadable_ (_stream_readable.js:410:10)\\n    at _stream_readable.js:403:7\"}","statusText":"Internal Server Error","statusCode":500,"status":500,"statusType":5,"info":false,"ok":false,"clientError":false,"serverError":true,"error":{"status":500,"method":"GET","url":"refresh/3b2a9391467d9286773782e0f55c38cc?deep=false"},"accepted":false,"noContent":false,"badRequest":false,"unauthorized":false,"notAcceptable":false,"notFound":false,"forbidden":false,"headers":{"server":"nginx/1.6.2","date":"Wed, 12 Oct 2016 13:36:19 GMT","content-type":"application/json; charset=utf-8","content-length":"882","connection":"keep-alive","x-powered-by":"Express","etag":"W/\"372-e7d73b10\""},"header":{"server":"nginx/1.6.2","date":"Wed, 12 Oct 2016 13:36:19 GMT","content-type":"application/json; charset=utf-8","content-length":"882","connection":"keep-alive","x-powered-by":"Express","etag":"W/\"372-e7d73b10\""},"type":"application/json","charset":"utf-8","body":{"error":true,"name":"Error","message":"Command line too large","stack":"Error: Command line too large\n    at ImapConnection.Connection._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1463:11)\n    at Parser.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:173:10)\n    at Parser.emit (events.js:95:17)\n    at Parser._resTagged (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:174:10)\n    at Parser._parse (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:138:16)\n    at Parser._tryread (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:82:15)\n    at CleartextStream.Parser._cbReadable (/usr/local/cozy/apps/emails/node_modules/imap/lib/Parser.js:53:12)\n    at CleartextStream.emit (events.js:92:17)\n    at emitReadable_ (_stream_readable.js:410:10)\n    at _stream_readable.js:403:7"}},"status":500}

Maybe @hmsuchier can explane me how the forced to set the trashMailbox parameter a bit deeper. Im no experienced web-developer until now... :)

And my second account doesn't show any mails in the folders. Its a imap account from a german provider that needs a path-prefix of INBOX to work. I know that from my Macbook Mail / Internet-Account settings. Is thats maybe some different bug?

Regards, Novski
